#!/bin/sh
# Обёртка вокруг робота, перезапускает его при падении.
# Обработчик исключений в роботе завершает работу с кодом 2.
while :; do
  python robot.py $*
  [ "$?" != "2" ] && exit
  echo "Non-clean shutdown, restarting."
done
