application: free-music
version: 1
runtime: python
api_version: 1

# Good example: http://code.google.com/p/rietveld/source/browse/trunk/app.yaml

handlers:
- url: /static/
  static_dir: static
- url: /doc/
  static_dir: doc
- url: .*
  script: main.py
