application: free-music
version: 2
runtime: python
api_version: 1

# Good example: http://code.google.com/p/rietveld/source/browse/trunk/app.yaml

handlers:
- url: /
  script: handlers.py
- url: /album/\d+(|/download)
  script: handlers.py
- url: /album/\d+/upload
  script: handlers.py
  login: admin
- url: /album/edit
  script: handlers.py
  login: admin
- url: /album/submit
  script: handlers.py
  login: admin
- url: /artist/[^/]+
  script: handlers.py
- url: /artists
  script: handlers.py
- url: /download/[^/]+/[^/]+
  script: handlers.py
- url: /file/serve/\d+/.+
  script: handlers.py
- url: /tag/[^/]+
  script: handlers.py
- url: /upload($|/callback$|/serve$)
  script: handlers.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.2.ico
  upload: static/favicon.2.ico
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
- url: /google4c14bfd1bdbab0dd.html
  static_files: static/google4c14bfd1bdbab0dd.html
  upload: static/google4c14bfd1bdbab0dd.html
- url: /static/
  static_dir: static
- url: /doc/
  static_dir: doc

- url: /(albums\.rss|album/.*)
  script: album.py
- url: /(artist/\d+|artist(\.rss)?)
  script: artist.py
- url: /labels(/cache)?
  script: labels.py
- url: /player
  script: player.py
- url: /radio(/.*)?
  script: radio.py
- url: /(users|u/[^/]+)
  script: users.py
- url: /edit
  script: edit.py

- url: .*
  script: main.py
