application: free-music
version: 3
runtime: python
api_version: 1

# Good example: http://code.google.com/p/rietveld/source/browse/trunk/app.yaml

handlers:

- url: /c/.*
  script: gaedir/server.py

- url: /favicon.ico
  static_files: fmh/static/favicon.ico
  upload: fmh/static/favicon.ico
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
- url: /google4c14bfd1bdbab0dd.html
  static_files: static/google4c14bfd1bdbab0dd.html
  upload: static/google4c14bfd1bdbab0dd.html
- url: /static/
  static_dir: static
- url: /fmh-static/
  static_dir: fmh/static
- url: /doc/
  static_dir: doc

- url: /pages/.*
  script: pages.py

- url: .*
  script: fmh/server.py

builtins:
- datastore_admin: on
