application: free-music
version: 1
runtime: python
api_version: 1

# Good example: http://code.google.com/p/rietveld/source/browse/trunk/app.yaml

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.2.ico
  upload: static/favicon.2.ico
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
- url: /google4c14bfd1bdbab0dd.html
  static_files: static/google4c14bfd1bdbab0dd.html
  upload: static/google4c14bfd1bdbab0dd.html
- url: /static/
  static_dir: static
- url: /doc/
  static_dir: doc

- url: /(albums\.rss|album/.*)
  script: album.py
- url: /(artist/fix|artist/\d+|artists(\.rss)?)
  script: artist.py
- url: /labels(/cache)?
  script: labels.py
- url: /player
  script: player.py
- url: /radio(/.*)?
  script: radio.py
- url: /upload/(queue|remote)
  script: upload.py
- url: /(users|u/[^/]+)
  script: users.py
- url: .*
  script: main.py
