application: freemusic
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static
- url: /doc/
  static_dir: doc
- url: /upload/.*
  script: upload.py
- url: .*
  script: main.py
